/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controller.ControllerUsuario;
import javax.swing.JOptionPane;

/**
 *
 * @author nicol
 */
public class frmUsuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmUsuario
     */
    public frmUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNombre = new javax.swing.JTextField();
        jlApellidoUsuario1 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        txtApellidoUsuario1 = new javax.swing.JTextField();
        txtApellidoUsuario2 = new javax.swing.JTextField();
        jlApellidoUsuario2 = new javax.swing.JLabel();
        jlEmailUsuario = new javax.swing.JLabel();
        txtEmailUsuario = new javax.swing.JTextField();
        txtNombreUsuario = new javax.swing.JTextField();
        jlNombreUsuario = new javax.swing.JLabel();
        jlPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        jlTipoUsuario = new javax.swing.JLabel();
        cmbTipoUsuario = new javax.swing.JComboBox<>();
        jlActivo = new javax.swing.JLabel();
        jlEnunciado = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableUsuario = new javax.swing.JTable();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblBuscar = new javax.swing.JLabel();
        jlUsuario = new javax.swing.JLabel();
        jlIdUsuario = new javax.swing.JLabel();
        txtidUsuario = new javax.swing.JTextField();
        jlNombreUsuarioNormal = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        cbxActivo = new javax.swing.JCheckBox();
        btnRefrescar = new javax.swing.JButton();

        setClosable(true);

        jlApellidoUsuario1.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        jlApellidoUsuario1.setText("Apellido 1:");

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });

        btnBuscar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBuscar.setText("Buscar");

        txtApellidoUsuario2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoUsuario2ActionPerformed(evt);
            }
        });

        jlApellidoUsuario2.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        jlApellidoUsuario2.setText("Apellido 2:");

        jlEmailUsuario.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        jlEmailUsuario.setText("Email:");

        jlNombreUsuario.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        jlNombreUsuario.setText("NombreUsuario:");

        jlPassword.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        jlPassword.setText("Password:");

        jlTipoUsuario.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        jlTipoUsuario.setText("Tipo de Usuario:");

        cmbTipoUsuario.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        cmbTipoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADMINISTRADOR", "ASISTENTE" }));

        jlActivo.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        jlActivo.setText("Activo:");

        jlEnunciado.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        jlEnunciado.setText("Digite la Información del usuario");

        tableUsuario.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        tableUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "Apellido 1", "Apellido 2", "Email", "Nombre Usuario", "Tipo de Usuario", "Password", "Activo"
            }
        ));
        tableUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableUsuarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableUsuario);

        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnGuardar.setText("Guardar");

        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCancelar.setText("Cancelar");

        lblBuscar.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        lblBuscar.setText("Buscar por Nombre Usuario");

        jlUsuario.setFont(new java.awt.Font("Lucida Bright", 0, 24)); // NOI18N
        jlUsuario.setText("Informacion del Usuario");

        jlIdUsuario.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        jlIdUsuario.setText("Id:");

        txtidUsuario.setEnabled(false);
        txtidUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidUsuarioActionPerformed(evt);
            }
        });

        jlNombreUsuarioNormal.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        jlNombreUsuarioNormal.setText("Nombre:");

        btnEliminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEliminar.setText("Eliminar");

        btnEditar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEditar.setText("Editar");

        cbxActivo.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        cbxActivo.setText("Activo / Inactivo");

        btnRefrescar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRefrescar.setText("Refrescar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlUsuario)
                            .addComponent(jlEnunciado)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jlTipoUsuario)
                                        .addComponent(jlPassword)
                                        .addComponent(jlActivo))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jlEmailUsuario)
                                        .addComponent(jlNombreUsuario)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNombreUsuario)
                                    .addComponent(txtEmailUsuario)
                                    .addComponent(cmbTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbxActivo, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlIdUsuario)
                                    .addComponent(jlNombreUsuarioNormal)
                                    .addComponent(jlApellidoUsuario1))
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtApellidoUsuario2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtApellidoUsuario1, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                                        .addComponent(txtNombre)
                                        .addComponent(txtidUsuario))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(btnBuscar)
                        .addGap(73, 73, 73))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnRefrescar)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminar)
                                .addGap(18, 18, 18)
                                .addComponent(btnEditar))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 875, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addComponent(jlApellidoUsuario2)
                    .addContainerGap(1240, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jlUsuario)
                .addGap(18, 18, 18)
                .addComponent(jlEnunciado)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBuscar)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlIdUsuario)
                    .addComponent(txtidUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEliminar)
                            .addComponent(btnEditar)
                            .addComponent(btnRefrescar))
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlNombreUsuarioNormal)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlApellidoUsuario1)
                            .addComponent(txtApellidoUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(txtApellidoUsuario2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlEmailUsuario)
                            .addComponent(txtEmailUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlNombreUsuario))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlTipoUsuario)
                            .addComponent(cmbTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlPassword))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxActivo)
                            .addComponent(jlActivo))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCancelar)
                            .addComponent(btnGuardar))))
                .addGap(42, 42, 42))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(276, 276, 276)
                    .addComponent(jlApellidoUsuario2)
                    .addContainerGap(362, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void txtApellidoUsuario2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoUsuario2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoUsuario2ActionPerformed

    private void tableUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableUsuarioMouseClicked
        try {
            int fila = tableUsuario.getSelectedRow();
            txtidUsuario.setText(tableUsuario.getValueAt(fila, 0).toString());
            txtNombre.setText(tableUsuario.getValueAt(fila, 1).toString());
            txtApellidoUsuario1.setText(tableUsuario.getValueAt(fila, 2).toString());
            txtApellidoUsuario2.setText(tableUsuario.getValueAt(fila, 3).toString());
            txtEmailUsuario.setText(tableUsuario.getValueAt(fila, 4).toString());
            txtNombreUsuario.setText(tableUsuario.getValueAt(fila, 5).toString());
            cmbTipoUsuario.setSelectedItem(tableUsuario.getValueAt(fila, 6));
            txtPassword.setText(tableUsuario.getValueAt(fila, 7).toString());
            cbxActivo.setSelected(Boolean.parseBoolean(tableUsuario.getValueAt(fila, 8).toString()));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al seleccionar un registro: " + e.getMessage());
        }
    }//GEN-LAST:event_tableUsuarioMouseClicked

    private void txtidUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBuscar;
    public javax.swing.JButton btnCancelar;
    public javax.swing.JButton btnEditar;
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnGuardar;
    public javax.swing.JButton btnRefrescar;
    public javax.swing.JCheckBox cbxActivo;
    public javax.swing.JComboBox<String> cmbTipoUsuario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlActivo;
    private javax.swing.JLabel jlApellidoUsuario1;
    private javax.swing.JLabel jlApellidoUsuario2;
    private javax.swing.JLabel jlEmailUsuario;
    private javax.swing.JLabel jlEnunciado;
    private javax.swing.JLabel jlIdUsuario;
    private javax.swing.JLabel jlNombreUsuario;
    private javax.swing.JLabel jlNombreUsuarioNormal;
    private javax.swing.JLabel jlPassword;
    private javax.swing.JLabel jlTipoUsuario;
    private javax.swing.JLabel jlUsuario;
    private javax.swing.JLabel lblBuscar;
    public javax.swing.JTable tableUsuario;
    public javax.swing.JTextField txtApellidoUsuario1;
    public javax.swing.JTextField txtApellidoUsuario2;
    public javax.swing.JTextField txtBuscar;
    public javax.swing.JTextField txtEmailUsuario;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JTextField txtNombreUsuario;
    public javax.swing.JTextField txtPassword;
    public javax.swing.JTextField txtidUsuario;
    // End of variables declaration//GEN-END:variables
}
