/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controller.ControllerDueno;
import Controller.ControllerMascota;
import Controller.ControllerUsuario;
import Controller.ControllerVeterinario;
import Controller.ControllerCita;
import Controller.ControllerReportes;
import java.io.File;

/**
 *
 * @author nicol
 */
public class frmVentanaPrincipal extends javax.swing.JFrame {
      
     public void permisoAdministradores(String tipoUsuario){
   
        if("ADMINISTRADOR".equals(tipoUsuario)){
          btnRegistroCitas.setVisible(false);   
        }   
    }
     
     public void permisoAsistentes(String tipoUsuario){
     
         if ("ASISTENTE".equals(tipoUsuario)) {
            btnVeterinario.setVisible(false);
            btnUsuario.setVisible(false);
         }   
     }
    /**
     * Creates new form frmVentanaPrincipal
     */
    public frmVentanaPrincipal(String idUsuario,String nombreUsuario,String tipoUsuario) {
        initComponents();
        setLocationRelativeTo(null);
        this.setExtendedState(MAXIMIZED_BOTH);
        setTitle("Sistem de registro de una veterinaria");
        lblIdUsuario.setText(idUsuario);
        lblNombreUsuario.setText(nombreUsuario);
        lblTipoUsuario.setText(tipoUsuario);
        permisoAdministradores(tipoUsuario);
        permisoAsistentes(tipoUsuario);    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        lblIdUsuario = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblTipoUsuario = new javax.swing.JLabel();
        lblNombreUsuario = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        btnSalir = new javax.swing.JMenuItem();
        menuCatalogoDeDatos = new javax.swing.JMenu();
        btnUsuario = new javax.swing.JMenuItem();
        btnDueno = new javax.swing.JMenuItem();
        btnVeterinario = new javax.swing.JMenuItem();
        btnMascota = new javax.swing.JMenuItem();
        menuAyuda = new javax.swing.JMenu();
        btnRegistroCitas = new javax.swing.JMenuItem();
        menuReportes = new javax.swing.JMenu();
        btnCitasFecha = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        btnCreditos = new javax.swing.JMenuItem();
        btnManual = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblIdUsuario.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        lblIdUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblIdUsuario.setText("Id Usuario");

        lblTipoUsuario.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        lblTipoUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblTipoUsuario.setText("Tipo de Usuario");

        lblNombreUsuario.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        lblNombreUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreUsuario.setText("Nombre de Usuario");

        desktopPane.setLayer(lblIdUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(lblTipoUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(lblNombreUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopPaneLayout.createSequentialGroup()
                .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(desktopPaneLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(desktopPaneLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(desktopPaneLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(lblTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(605, Short.MAX_VALUE))
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopPaneLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(lblIdUsuario)
                .addGap(18, 18, 18)
                .addComponent(lblNombreUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTipoUsuario)
                .addContainerGap(273, Short.MAX_VALUE))
        );

        menuArchivo.setText("Archivo");

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        menuArchivo.add(btnSalir);

        jMenuBar1.add(menuArchivo);

        menuCatalogoDeDatos.setText("Catalogo de datos");

        btnUsuario.setText("Usuario");
        btnUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioActionPerformed(evt);
            }
        });
        menuCatalogoDeDatos.add(btnUsuario);

        btnDueno.setText("Dueño");
        btnDueno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDuenoActionPerformed(evt);
            }
        });
        menuCatalogoDeDatos.add(btnDueno);

        btnVeterinario.setText("Veterinario");
        btnVeterinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVeterinarioActionPerformed(evt);
            }
        });
        menuCatalogoDeDatos.add(btnVeterinario);

        btnMascota.setText("Mascota");
        btnMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMascotaActionPerformed(evt);
            }
        });
        menuCatalogoDeDatos.add(btnMascota);

        jMenuBar1.add(menuCatalogoDeDatos);

        menuAyuda.setText("Gestión de Procesos");

        btnRegistroCitas.setText("Registro de Citas");
        btnRegistroCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroCitasActionPerformed(evt);
            }
        });
        menuAyuda.add(btnRegistroCitas);

        jMenuBar1.add(menuAyuda);

        menuReportes.setText("Reportes");

        btnCitasFecha.setText("Citas por Fecha-Dueño");
        btnCitasFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCitasFechaActionPerformed(evt);
            }
        });
        menuReportes.add(btnCitasFecha);

        jMenuBar1.add(menuReportes);

        jMenu1.setText("Acerca de");

        btnCreditos.setText("Creditos");
        btnCreditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreditosActionPerformed(evt);
            }
        });
        jMenu1.add(btnCreditos);

        btnManual.setText("Manual de Usuario");
        btnManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManualActionPerformed(evt);
            }
        });
        jMenu1.add(btnManual);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioActionPerformed
        frmUsuario frmU = new frmUsuario();
        desktopPane.add(frmU);
        ControllerUsuario con = new ControllerUsuario(frmU);
        con.iniciar();
        frmU.toFront();
        frmU.setLocation(desktopPane.getWidth() / 2 - frmU.getWidth() / 2, desktopPane.getHeight() / 2 - frmU.getHeight() / 2);
        frmU.setVisible(true);

    }//GEN-LAST:event_btnUsuarioActionPerformed

    private void btnDuenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDuenoActionPerformed
        frmDueno frmD = new frmDueno();
        desktopPane.add(frmD);
        ControllerDueno con = new ControllerDueno(frmD);
        con.iniciar();
        frmD.toFront();
        frmD.setLocation(desktopPane.getWidth() / 2 - frmD.getWidth() / 2, desktopPane.getHeight() / 2 - frmD.getHeight() / 2);
        frmD.setVisible(true);
    }//GEN-LAST:event_btnDuenoActionPerformed

    private void btnVeterinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVeterinarioActionPerformed
        frmVeterinario frmV = new frmVeterinario();
        desktopPane.add(frmV);
        ControllerVeterinario con = new ControllerVeterinario(frmV);
        con.iniciar();
        frmV.toFront();
        frmV.setLocation(desktopPane.getWidth() / 2 - frmV.getWidth() / 2, desktopPane.getHeight() / 2 - frmV.getHeight() / 2);
        frmV.setVisible(true);

    }//GEN-LAST:event_btnVeterinarioActionPerformed

    private void btnCitasFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCitasFechaActionPerformed
        // TODO add your handling code here:
        frmReportes frmRegistro = new frmReportes();
        desktopPane.add(frmRegistro);
        ControllerReportes con = new ControllerReportes(frmRegistro);
        con.iniciar();
        frmRegistro.toFront();
        frmRegistro.setLocation(desktopPane.getWidth() / 2 - frmRegistro.getWidth() / 2, desktopPane.getHeight() / 2 - frmRegistro.getHeight() / 2);
        frmRegistro.setVisible(true);  
    }//GEN-LAST:event_btnCitasFechaActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMascotaActionPerformed
        // TODO add your handling code here:
        frmMascota frmM = new frmMascota();
        desktopPane.add(frmM);
        ControllerMascota con = new ControllerMascota(frmM);
        con.iniciar();
        frmM.toFront();
        frmM.setLocation(desktopPane.getWidth() / 2 - frmM.getWidth() / 2, desktopPane.getHeight() / 2 - frmM.getHeight() / 2);
        frmM.setVisible(true);
    }//GEN-LAST:event_btnMascotaActionPerformed

    private void btnRegistroCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroCitasActionPerformed
        // TODO add your handling code here:
        frmRegistroCitas frmR = new frmRegistroCitas();
        desktopPane.add(frmR);
        ControllerCita con = new ControllerCita(frmR);
        con.iniciar();
        frmR.toFront();
        frmR.setLocation(desktopPane.getWidth() / 2 - frmR.getWidth() / 2, desktopPane.getHeight() / 2 - frmR.getHeight() / 2);
        frmR.setVisible(true);
    }//GEN-LAST:event_btnRegistroCitasActionPerformed

    private void btnCreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreditosActionPerformed
        // TODO add your handling code here:
        frmCreditos frmCredits = new frmCreditos();
        desktopPane.add(frmCredits);
        new frmCreditos().setVisible(true);
        frmCredits.toFront();
        frmCredits.setLocation(desktopPane.getWidth() / 2 - frmCredits.getWidth() / 2, desktopPane.getHeight() / 2 - frmCredits.getHeight() / 2);
        frmCredits.setVisible(true);
    }//GEN-LAST:event_btnCreditosActionPerformed

    private void btnManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManualActionPerformed
        // TODO add your handling code here:

        try {
            String path = ".\\ManualUsuario\\Manualdeusuario.pdf";
               
            File file = new File (path);
            if (file.exists()){
                
                Process pro = Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler "+ path);
            }else{
            
            }
        } catch (Exception e) {
        }

    }//GEN-LAST:event_btnManualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmVentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmVentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmVentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmVentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmVentanaPrincipal(lblIdUsuario.getText(), lblNombreUsuario.getText(), lblTipoUsuario.getText()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnCitasFecha;
    private javax.swing.JMenuItem btnCreditos;
    private javax.swing.JMenuItem btnDueno;
    private javax.swing.JMenuItem btnManual;
    private javax.swing.JMenuItem btnMascota;
    private javax.swing.JMenuItem btnRegistroCitas;
    private javax.swing.JMenuItem btnSalir;
    private javax.swing.JMenuItem btnUsuario;
    private javax.swing.JMenuItem btnVeterinario;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    public static javax.swing.JLabel lblIdUsuario;
    public static javax.swing.JLabel lblNombreUsuario;
    public static javax.swing.JLabel lblTipoUsuario;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JMenu menuCatalogoDeDatos;
    private javax.swing.JMenu menuReportes;
    // End of variables declaration//GEN-END:variables
}
